### ISSUE TITLE
播放器使用url资源在 seeking 状态下, 执行 stop / destroy后加载请求依然在执行

### ISSUE THREAD

**Issue by xuanhen2013** [zhaohappy/libmedia#30]
视频在线地址: https://vip.123pan.cn/1831933142/12534362

具体日志
```
vue.js:9099 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
vue.js:9108 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
avplayer.js:1 [src/avplayer/AVPlayer.ts][line 3479] [info] set log level: 1
avplayer.html:1398 atomic support
avplayer.js:1 [src/avplayer/AVPlayer.ts][line 437] [info] create player, taskId: d2692cf8-c655-4617-9529-d90efaa64e10
avplayer.js:1 [src/avplayer/AVPlayer.ts][line 1001] [info] call load, taskId: d2692cf8-c655-4617-9529-d90efaa64e10
avplayer.js:1 [src/avplayer/AVPlayer.ts][line 1410] [info] 
AVPlayer version v0.1.1-57-gd85d7f2 Copyright (c) 2024-present the libmedia developers
Input #0, mp4, from 'https://vip.123pan.cn/1831933142/12534362':
  Duration: 00:01:32.970, start: 00:00:00.000, bitrate: 199435 kbps/s
  Stream #0:0 Video: h264 (High), yuv420p(tv, bt709), 1920x1080 [SAR: 1:1 DAR 16:9], 2911 kbps/s, 30.00 fps, 30.00 tbr, 30 tbn (default) 
    Metadata:
      creationTime: 3741736162
      modificationTime: 3741736378
      matrix: [1,0,0,0,1,0,0,0,1]
      language: 21956
      languageString: und
      handlerName: 
      vendorId: 
      encoder: 
      naluLengthSizeMinusOne: 3
  Stream #0:1 Audio: aac (LC), 48000 Hz, stereo, float-planar, 196523 kbps/s (default) 
    Metadata:
      creationTime: 3741736036
      modificationTime: 3741736378
      language: 21956
      languageString: und
      handlerName: 
      vendorId: 

avplayer.js:1 [src/avplayer/AVPlayer.ts][line 1432] [info] call play, options: {"audio":true,"video":true,"subtitle":true}, status: 4 taskId: d2692cf8-c655-4617-9529-d90efaa64e10
ceb07c7c-0dca-4f97-a9a8-79cdabfdffec:178 [src/avpipeline/DemuxPipeline.ts][line 616] [debug] connect stream 0, taskId: d2692cf8-c655-4617-9529-d90efaa64e10
ceb07c7c-0dca-4f97-a9a8-79cdabfdffec:178 [src/avpipeline/DemuxPipeline.ts][line 616] [debug] connect stream 1, taskId: d2692cf8-c655-4617-9529-d90efaa64e10
avplayer.js:1 [src/avplayer/AVPlayer.ts][line 2476] [info] player call setVolume, set 1, used 1, taskId: d2692cf8-c655-4617-9529-d90efaa64e10
ceb07c7c-0dca-4f97-a9a8-79cdabfdffec:178 [src/avpipeline/DemuxPipeline.ts][line 876] [debug] start demux loop, taskId: d2692cf8-c655-4617-9529-d90efaa64e10
b23bfe00-4ce8-42df-8f64-0f3dc9e51baf:178 [src/avpipeline/AudioRenderPipeline.ts][line 230] [debug] got first audio frame, pts: 0(0ms), taskId: d2692cf8-c655-4617-9529-d90efaa64e10
avplayer.js:1 [src/avplayer/AVPlayer.ts][line 3175] [info] first audio frame rendered, taskId: d2692cf8-c655-4617-9529-d90efaa64e10
e0d6ea96-8d2d-4c02-a3f5-6bf99282144d:178 [src/avpipeline/VideoRenderPipeline.ts][line 481] [debug] got first video frame, pts: 2(66ms), taskId: d2692cf8-c655-4617-9529-d90efaa64e10
avplayer.js:1 [src/avplayer/AVPlayer.ts][line 3167] [info] first video frame rendered, taskId: d2692cf8-c655-4617-9529-d90efaa64e10
e0d6ea96-8d2d-4c02-a3f5-6bf99282144d:178 [src/avpipeline/VideoRenderPipeline.ts][line 237] [debug] video render sync pts accelerate, targetPTS: 922, currentPTS: 800, diff: 122, taskId: d2692cf8-c655-4617-9529-d90efaa64e10
e0d6ea96-8d2d-4c02-a3f5-6bf99282144d:178 [src/avpipeline/VideoRenderPipeline.ts][line 564] [debug] video render accelerate startTimestamp sub: 100, taskId: d2692cf8-c655-4617-9529-d90efaa64e10
e0d6ea96-8d2d-4c02-a3f5-6bf99282144d:178 [src/avpipeline/VideoRenderPipeline.ts][line 564] [debug] video render accelerate startTimestamp sub: 22, taskId: d2692cf8-c655-4617-9529-d90efaa64e10
avplayer.js:1 [src/avplayer/AVPlayer.ts][line 2120] [info] call seek, timestamp: 53716, taskId: d2692cf8-c655-4617-9529-d90efaa64e10
b23bfe00-4ce8-42df-8f64-0f3dc9e51baf:178 [src/avpipeline/AudioRenderPipeline.ts][line 616] [debug] wait current pull front frame before seek, taskId: d2692cf8-c655-4617-9529-d90efaa64e10
e0d6ea96-8d2d-4c02-a3f5-6bf99282144d:178 [src/avpipeline/VideoRenderPipeline.ts][line 900] [debug] before seek end, taskId: d2692cf8-c655-4617-9529-d90efaa64e10
b23bfe00-4ce8-42df-8f64-0f3dc9e51baf:178 [src/avpipeline/AudioRenderPipeline.ts][line 647] [debug] before seek end, taskId: d2692cf8-c655-4617-9529-d90efaa64e10
ceb07c7c-0dca-4f97-a9a8-79cdabfdffec:178 [src/avformat/demux.ts][line 582] [debug] seek in video stream, streamIndex: 0, timestamp: 53716, flags: 8

// 点击 stop

avplayer.js:1 [src/avplayer/AVPlayer.ts][line 2257] [info] call stop, taskId: d2692cf8-c655-4617-9529-d90efaa64e10
avplayer.js:1 [src/avplayer/AVPlayer.ts][line 2041] [debug] seeked to packet timestamp: 52033, taskId: d2692cf8-c655-4617-9529-d90efaa64e10
232e3ad8-d617-4106-8bd2-c3befb51d534:178 [src/avpipeline/AudioDecodePipeline.ts][line 349] [info] reset audio decoder, taskId: d2692cf8-c655-4617-9529-d90efaa64e10
d8e19a0a-13b3-4c91-999d-eaa7d5ec8cd8:178 [src/avpipeline/VideoDecodePipeline.ts][line 717] [info] reset video decoder, taskId: d2692cf8-c655-4617-9529-d90efaa64e10
e0d6ea96-8d2d-4c02-a3f5-6bf99282144d:178 [src/avpipeline/VideoRenderPipeline.ts][line 950] [debug] sync seek time end, taskId: d2692cf8-c655-4617-9529-d90efaa64e10
b23bfe00-4ce8-42df-8f64-0f3dc9e51baf:178 [src/avpipeline/AudioRenderPipeline.ts][line 708] [debug] sync seek time end, taskId: d2692cf8-c655-4617-9529-d90efaa64e10
b23bfe00-4ce8-42df-8f64-0f3dc9e51baf:178 [src/avpipeline/AudioRenderPipeline.ts][line 730] [debug] after seek end, taskId: d2692cf8-c655-4617-9529-d90efaa64e10
e0d6ea96-8d2d-4c02-a3f5-6bf99282144d:178 [src/avpipeline/VideoRenderPipeline.ts][line 985] [debug] got first video frame, pts: 1614(53800ms), taskId: d2692cf8-c655-4617-9529-d90efaa64e10

// 这里重新点击 load 会报错

avplayer.js:1 [src/avplayer/AVPlayer.ts][line 1001] [info] call load, taskId: d2692cf8-c655-4617-9529-d90efaa64e10
avplayer.js:1 [src/avplayer/AVPlayer.ts][line 1166] [error] register io task failed, ret: -5, taskId: d2692cf8-c655-4617-9529-d90efaa64e10
avplayer.js:1 Uncaught (in promise) Error: [src/avplayer/AVPlayer.ts][line 1166] [fatal]: register io task failed, ret: -5, taskId: d2692cf8-c655-4617-9529-d90efaa64e10
    at Object.x (avplayer.js:1:602863)
    at Et.load (avplayer.js:1:172799)
x @ avplayer.js:1
load @ avplayer.js:1
await in load
loadPlayer @ avplayer.html:772
onclick @ avplayer.html:375
player.status
3
```

**Comment by zhaohappy** [comment]
player 的方法都是异步的，外面需要自己保证一个操作结束之后接着执行下一个操作。否则状态会打乱。

**Comment by zhaohappy** [comment]
优化 seeking 状态下可以 stop，其他 api 调用需要外面保证时序。seeking 比较特殊，时间可能比较长，不处理 stop 要等好久。
